version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://weSmartUser:your_password@db:5432/weSmartDB
      - JWT_SECRET=your_jwt_secret
      - WHATSAPP_API_URL=https://graph.facebook.com/v17.0/YOUR_PHONE_NUMBER_ID/messages
      - WHATSAPP_ACCESS_TOKEN=YOUR_ACCESS_TOKEN
      - WEBHOOK_VERIFY_TOKEN=your_verify_token
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: weSmartUser
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: weSmartDB
    volumes:
      - db-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount custom config
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"   # Expose Grafana on port 3001
    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9101:9100"   # Changed host port to 9101 to avoid conflicts

volumes:
  db-data:
