version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://weSmartUser:your_password@db:5432/weSmartDB
      - JWT_SECRET=your_jwt_secret
      - WHATSAPP_API_URL=https://graph.facebook.com/v17.0/YOUR_PHONE_NUMBER_ID/messages
      - WHATSAPP_ACCESS_TOKEN=YOUR_ACCESS_TOKEN
      - WEBHOOK_VERIFY_TOKEN=your_verify_token
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: weSmartUser
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: weSmartDB
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
